apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users-api-deployment-green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users-api-green
    spec:
      containers:
      - name: users-api-green
        image: index.docker.io/mateuszdyminski/zero-java:v2
        imagePullPolicy: Always
        ports:
          - containerPort: 8080