apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users-go-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: users-go-api
        serviceName: users-go-api
    spec:
      containers:
      - name: users-go-api
        image: index.docker.io/mateuszdyminski/zero-golang:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
