apiVersion: v1
kind: Service
metadata:
  name: users-go-api-green
  labels:
    app: users-go-api
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31003
  selector:
    app: users-go-api-green